spring:
  # 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zero-admin?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    port: 6379
  resources:
    # 访问系统外部资源，将该目录下的文件映射到系统下
    static-locations: file:/usr/web-project/zero-admin/static/
zero:
  domain-name: http://zeroadmin.herenpeng.com
  common:
    # Swagger文档配置
    swagger:
      # 是否启用Swagger文档
      enable: true
  upload:
    # 文件上传目标路径
    path: /usr/web-project/zero-admin/static/
logging:
  config: classpath:logback-spring-prod.xml