server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zero-admin
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
# MyBatisPlus的相关配置
mybatis-plus:
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除字段
  global-config:
    db-config:
      # 删除状态为1(true)
      logic-delete-value: true
      # 没有删除状态为0(false)
      logic-not-delete-value: false
zero:
  sys:
    user:
      root-username: root
      root-password: root
      default-password: 111111
    role:
      root-name: root
    security:
      jwt:
        secret: HdGkiOiI4ODgiLCJzdWIiOiLlsI
        ttl: 3600000
        issuer: https://www.zero.com
        key: accessToken
    listener:
      execution-start: true
      execution-stop: true
      event:
        scan-resources: true
        destroy-resources: false

