server:
  # 项目启动端口
  port: 10000
  # 项目请求前缀
  servlet:
    context-path: /api
  # tomcat字符编码
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    # Spring应用名称
    name: zero-admin
  # Jackson相关配置
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  # SpringMail发送邮件相关配置
  mail:
    # smtp服务主机  qq邮箱的服务主机为smtp.qq.com
    host: smtp.qq.com
    # 服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    # 发送邮件的账号名
    username: xxxxxxxxxxxx@qq.com
    # 授权码
    password: xxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  profiles:
    active: dev
# MyBatisPlus的相关配置
mybatis-plus:
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
    # 打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除字段
  global-config:
    db-config:
      # 删除状态为1(true)
      logic-delete-value: true
      # 没有删除状态为0(false)
      logic-not-delete-value: false
zero:
  sys:
    user:
      # root用户默认用户名
      root-username: root
      # root用户默认密码
      root-password: 111111
      # 普通用户默认密码
      default-password: 111111
    role:
      # root角色默认角色名
      root-name: root
      # root角色默认描述信息
      root-description: root权限，系统的最高权限
    security:
      jwt:
        secret: HdGkiOiI4ODgiLCJzdWIiOiLlsI
        ttl: 3600000
        issuer: http://zeroadmin.herenpeng.com
        key: accessToken
    listener:
      execution-start: true
      execution-stop: true
  # 邮件模板内容
  mail:
    template:
      verify:
        subject: 邮箱验证码
        path: /templates/mail
        file: verify.ftl


